name: Prepare for release

on:
  workflow_dispatch:
    inputs:
      version-bump:
        description: 'Release type'
        required: true
        type: choice
        options:
        - major
        - minor
        - patch
        default: patch
    test-wheels:
      description: 'Run integration tests on wheels'
      default: true
      type: boolean

jobs:
  bump-version:
    outputs:
      new-version: ${{ steps.bump-version.outputs.new_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: stage
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - run: pip install semver
      - name: Bump version
        id: bump-version
        run: |
          currentVersion=$(cat VERSION)
          newVersion=$(pysemver bump ${{ github.event.inputs.version-bump }} $currentVersion)
          # Update repo files
          echo $newVersion > VERSION
          sed -i "s/const char version\[8] = \".*\";/const char version\[8] = \"${newVersion}\";/" src/main/aerospike.c
          # Allow following steps to get new version
          echo "NEW_VERSION=$newVersion" >> $GITHUB_ENV
          # Also pass new version to build wheels workflow
          echo "new_version=$newVersion" >> $GITHUB_OUTPUT
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Bump to $newVersion
          branch: bump-to-$newVersion
          add-paths: src/main/aerospike.c, VERSION
          commit-message: Bump version to ${{ env.NEW_VERSION }}
          delete-branch: true


      # - name: Create release notes
      #   uses: release-drafter/release-drafter@v5
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Create draft release in Github
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     draft: true

  build-wheels:
    needs: bump-version
    uses: aerospike/aerospike-client-python/.github/workflows/build-wheels.yml@${{needs.bump-version.outputs.new_version}}
    with:
      test-wheels: ${{ github.event.inputs.test-wheels }}
